In [1]:
import torch

In [2]:
shape = (3, 4)

In [20]:
ten = torch.randn(3, 4)
copy = torch.zeros_like(ten, dtype = torch.float)
print(ten)
print(copy)

tensor([[-1.3175, -0.7920, -0.9353,  0.0414],
        [-1.2458,  1.4573, -0.2918,  0.7974],
        [ 0.2432, -0.3551, -0.7857, -0.4213]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [9]:
ten[0,0].item()

0.0

In [21]:
# shape, type, device
ten.shape


torch.Size([3, 4])

In [24]:
ten.dtype

torch.float32

In [23]:
ten.device

device(type='cpu')

In [25]:
ten.data

tensor([[-1.3175, -0.7920, -0.9353,  0.0414],
        [-1.2458,  1.4573, -0.2918,  0.7974],
        [ 0.2432, -0.3551, -0.7857, -0.4213]])

In [27]:
param = torch.rand_like(ten, requires_grad=True)

In [33]:
param.requires_grad

True

In [ ]:
# compute z = x.y
# y = a + b

In [34]:
a = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(3.0, requires_grad = True)
x = torch.tensor(4.0, requires_grad = True)

In [36]:
y = a + b
z = x*y

In [37]:
z

tensor(20., grad_fn=<MulBackward0>)

In [38]:
z.grad_fn

In [39]:
y.grad_fn

In [41]:
x.grad_fn

In [42]:
a.grad_fn